### ISSUE TITLE
GUI use previous message on startup

### ISSUE THREAD

**Issue by borisliao** [borisliao/mbox#10]
**Is your feature request related to a problem? Please describe.**
Currently the bot deletes all messages in the command channel and resends all the GUI back again. This slows down startup time since it has to delete all the messages and resend it again. Additionally if a user hasn't muted the command channel, it spams notifications.

**Describe the solution you'd like**
The bot should be smarter, checking if the GUI is already sent in the channel, and only delete the messages that isn't part of the GUI. Additionally it should check if the buttons is already sent in the messages.

**Describe alternatives you've considered**
Checking if the buttons is already sent in the messages might fail if the discord API does not give on_reaction_added events to reactions longer then 3 days.

https://github.com/borisliao/mbox/blob/674f1eaf3cc4a0d0607239aa69bfb49eb1a930cf/src/commander/messenger.py#L124

**Comment by borisliao** [comment]
#77 will probably fix this issue

**Comment by Exsects** [comment]
Relate to #78 and #85
