### ISSUE TITLE
Create a Workflow for branches, build and deployments

### ISSUE THREAD

**Issue by Karan-Jain** [borisliao/mbox#32]
**As a** developer,
**I want to** put a workflow in place
**so that** I can manage the project more effectively 

**Acceptance Criteria:**

- In the actions tab create a custom/predefined workflow 
- build a pipeline
- create and manage branches
- do code and quality checks 
- add artifacts(optional)

**Estimated Time:**  TBD

**Comment by borisliao** [comment]
There is a testing folder guideline at https://github.com/borisliao/mbox/tree/master/test however the variables in samples.py needs to be mocked before test files can be made.

**Comment by Karan-Jain** [comment]
I suggest we hold a meeting to figure out testing frameworks

Quick things that come to mind...
1) pytest for unit testing with the mocking library....
2) behave for integration testing ( not sure if its applicable)
