### ISSUE TITLE
Restructure Codebase Using Cogs

### ISSUE THREAD

**Issue by Exsects** [borisliao/mbox#35]
**Is your feature request related to a problem? Please describe.**
Codebase is currently hard to maintain and understand. 

**Describe the solution you'd like**
Use cogs are recommended by [discord.py documentation](https://discordpy.readthedocs.io/en/stable/ext/commands/cogs.html?highlight=cogs) in which we can use to greatly enhance readability and improve our code quality. 

**Describe alternatives you've considered**
None

**Additional context**
I found a Discord Bot repo, who were able to successfully organize their code using cogs, which we can potentially use as a helpful reference.

Link: https://github.com/DenverCoder1/jct-discord-bot

**Comment by borisliao** [comment]
During the cog refactoring, make sure you put slash commands in a separate file
